
fastlane_version "2.26.1"

default_platform :ios

platform :ios do

  desc "Run unit tests and check library"
  lane :test do
    scan(workspace: "Pageboy.xcworkspace", scheme: "Pageboy iOS", clean: true, device: "iPhone 15 (18.0)") 
    pod_lib_lint(allow_warnings: true)
  end

  desc "Deploy a new version to CocoaPods and GitHub"
  lane :deploy do
    test

    podspec = "Pageboy.podspec"
    version = version_get_podspec(path: podspec)

    # Push new Github release
    github_release = set_github_release(
      repository_name: "uias/Pageboy",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: version,
      tag_name: version,
      description: "#{version} release.",
      commitish: "main"
    )

    # Push spec
    pod_push(allow_warnings: true, verbose: true)

    slack(
      message: "Pageboy v#{version} released!" 
    )
  end
end