name: Build
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Prepare
        run: |
          bundle update --bundler
          bundle install
      - name: Run tests
        run: bundle exec fastlane test
